In [1]:
import numpy

In [2]:
x = [1,2,3,4,5,67]
arr = numpy.array(x)
arr

array([ 1,  2,  3,  4,  5, 67])

In [3]:
arr1 = numpy.array([1,2,3,45,5])
arr1

array([ 1,  2,  3, 45,  5])

In [4]:
arr2 = numpy.array((32,3,4,5,6,76))
arr2

array([32,  3,  4,  5,  6, 76])

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr2.dtype

dtype('int32')

### Declaring dtype on creation

In [7]:
arr3 = numpy.array([1,2,3,4,5,6], dtype='float64')
arr3

array([1., 2., 3., 4., 5., 6.])

In [8]:
arr4 = numpy.array(['hello', 'world'], dtype='int32') #strings cannot do this
arr4

ValueError: invalid literal for int() with base 10: 'hello'

In [9]:
arr5 = numpy.array(['4','3'], dtype='float64')
arr5

array([4., 3.])

### Generating an array
For generating an array, we use arrange function

In [10]:
arr6 = numpy.arange(0, 10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr7 = numpy.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
arr8 = numpy.arange(0, 20, 2)
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Generating array with Zeros and Ones

In [13]:
arr9 = numpy.zeros(5, dtype='int32') #by default float value 
arr9

array([0, 0, 0, 0, 0])

In [14]:
arr10 = numpy.ones(5, dtype='int32')
arr10

array([1, 1, 1, 1, 1])

## Performing Arithmatic Operation on Array Elements

In [15]:
arr11 = numpy.arange(10, 21)
print(arr11)

[10 11 12 13 14 15 16 17 18 19 20]


In [16]:
arr11 + 20

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [17]:
arr11 * 3

array([30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60])

In [18]:
arr12 = numpy.arange(30, 51, 2)
arr12

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [19]:
print(arr11)
print(arr12)

[10 11 12 13 14 15 16 17 18 19 20]
[30 32 34 36 38 40 42 44 46 48 50]


In [20]:
arr11 + arr12

array([40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70])

In [21]:
arr11 // arr12 #floor division

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [22]:
arr11 ** arr12

array([ 1073741824, -1419655807,           0, -1072164847,           0,
        -384333439,           0,   621180097,           0,  -124641599,
                 0], dtype=int32)

In [23]:
arr11 * arr12

array([ 300,  352,  408,  468,  532,  600,  672,  748,  828,  912, 1000])

In [24]:
arr11 / arr12

array([0.33333333, 0.34375   , 0.35294118, 0.36111111, 0.36842105,
       0.375     , 0.38095238, 0.38636364, 0.39130435, 0.39583333,
       0.4       ])

In [25]:
arr13 = arr11 + arr12
arr13

array([40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70])

### CRUD Operations

In [26]:
arr14 = numpy.arange(20, 45, 3)
arr14

array([20, 23, 26, 29, 32, 35, 38, 41, 44])

In [27]:
arr14[3]

29

In [28]:
arr14[3] = 87 
arr14

array([20, 23, 26, 87, 32, 35, 38, 41, 44])

In [29]:
arr14[3] = arr14[3] + 3
arr14

array([20, 23, 26, 90, 32, 35, 38, 41, 44])

Delete Operations

In [30]:
arr14

array([20, 23, 26, 90, 32, 35, 38, 41, 44])

In [31]:
numpy.delete(arr14, 5) #create a new array    #deleting a single element #they are like return functions store value variable
arr14                  #executes privious value of arr14

array([20, 23, 26, 90, 32, 35, 38, 41, 44])

In [32]:
arr15 = numpy.delete(arr14, 5)
arr15

array([20, 23, 26, 90, 32, 38, 41, 44])

In [33]:
arr14 = numpy.delete(arr14, 5)
arr14

array([20, 23, 26, 90, 32, 38, 41, 44])

In [34]:
arr14

array([20, 23, 26, 90, 32, 38, 41, 44])

In [35]:
arr14 = numpy.delete(arr14, [1,3,5])
arr14

array([20, 26, 32, 41, 44])

Adding New Elements in an existing array

In [36]:
arr14

array([20, 26, 32, 41, 44])

In [37]:
#appending single element
arr14 = numpy.append(arr14, 65)  #return functions have to store value in variable 
arr14

array([20, 26, 32, 41, 44, 65])

In [38]:
#appending multiple elements
arr14 = numpy.append(arr14, [23,53,23,64,23,57])
arr14

array([20, 26, 32, 41, 44, 65, 23, 53, 23, 64, 23, 57])

### Practice Program

Write a program to generate array of 20 random numbers.
 Range of each element will be between 0, 1000 

In [46]:
import random
n=20
arr15 = []
while(n>0):
    random_num = random.randint(0,1000)
    arr15 = numpy.append(arr15, random_num)
    n=n-1
arr15

array([532., 597., 392., 275., 105., 427., 533., 495., 199., 790., 718.,
       136., 860., 309.,  82., 688., 125., 166., 323., 978.])

In [45]:
import random
lst = []
for i in range(20):
    lst.append(random.randint(0, 1000))
print(lst)
arr15 = numpy.array(lst, dtype='int32')
arr15

[626, 81, 614, 910, 868, 247, 534, 287, 590, 895, 116, 341, 523, 764, 838, 572, 548, 175, 701, 185]


array([626,  81, 614, 910, 868, 247, 534, 287, 590, 895, 116, 341, 523,
       764, 838, 572, 548, 175, 701, 185])

In [48]:
arr16 = numpy.array([], dtype='int32') #can make array this way also


## Time and Space Comparison between list and array

### Space Comparison

In [52]:
import sys

lst1 = list(range(1, 1000001))

arr17 = numpy.arange(1, 1000001)

print('Size of List ', sys.getsizeof(lst1)) #returns in bytes
print('Size of Array ', sys.getsizeof(arr17))

Size of List  8000056
Size of Array  4000104


### Time Comparison

In [53]:
import time

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

array1 = numpy.array(list1)
array2 = numpy.array(list2)

In [67]:
initial_list_time = time.time()
new_list = [(a*b) for a,b in zip(list1, list2)]
resultant_list_time = time.time()

print('Time taken by list in second ', resultant_list_time-initial_list_time)

Time taken by list in second  0.008002996444702148


In [68]:
initial_array_time = time.time()

new_array = array1 * array2

resultant_array_time = time.time()

print('Time taken by array in second', resultant_array_time-initial_array_time)

Time taken by array in second 0.0
