In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr.shape

(10,)

### 2-D Array

In [6]:
lst = [
    [1,2,3,4],
    [5,6,7,8]
]

arr2 = np.array(lst)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr2.shape

(2, 4)

In [9]:
arr2.ndim

2

### Changing Shape of Array

In [11]:
arr.shape

(10,)

In [16]:
arr3 = arr.reshape(2,5)

In [18]:
arr4 = arr.reshape(5,2)

In [19]:
arr4

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Iterating 2-D Array

In [20]:
arr4.shape

(5, 2)

In [22]:
print('Rows-', arr4.shape[0])
print('Columns-', arr4.shape[1])

Rows- 5
Columns- 2


####  Indexing of 2-D Array

In [28]:
print(arr4)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [29]:
print(arr4[3])  # Prints 4th element of the main array

[7 8]


In [31]:
print(arr4[3][1])  # Prints 2nd element of subarray number 4

8


In [41]:
for row in range(0, arr4.shape[0]):
    for col in range(0, arr4.shape[1]):
        print(arr4[row][col], end=' ')
    print()

1 2 
3 4 
5 6 
7 8 
9 10 


### Arithmatic Operations on Metrics

##### Addition

In [43]:
met1 = np.array([[1,3,4], [2,4,3], [3,4,5]])
met2 = np.array([[1,3,4], [2,4,3],[1,2,4]])

In [44]:
met3 = met1 + met2

In [45]:
print(met3)

[[2 6 8]
 [4 8 6]
 [4 6 9]]


In [48]:
met4 = np.add(met1, met2)
print(met4)

[[2 6 8]
 [4 8 6]
 [4 6 9]]


##### Subrtaction

In [49]:
met1 = np.array([[2,4,6],[4,2,2],[2,4,2]])
met2 = np.array([[1,2,3],[2,1,1],[1,2,1]])

In [50]:
met3 = met1 - met2

print(met3)

[[1 2 3]
 [2 1 1]
 [1 2 1]]


In [51]:
met4 = np.subtract(met1, met2)
print(met4)

[[1 2 3]
 [2 1 1]
 [1 2 1]]


In [53]:
met4.shape

(3, 3)

##### Multiplication

In [54]:
met1 = np.array([[1,2,3],[4,5,6]])
met2 = np.array([[10,11],[20,21],[30,31]])

In [58]:
met3 = np.dot(met1, met2)
print(met3)

[[140 146]
 [320 335]]


### Copy an Array 

In [59]:
ar10 = np.array([[10,11],[20,21],[30,31]])

In [61]:
ar10

array([[10, 11],
       [20, 21],
       [30, 31]])

In [62]:
ar10_copy = ar10

In [63]:
ar10_copy

array([[10, 11],
       [20, 21],
       [30, 31]])

In [64]:
ar10_copy[1][1] = 56

In [65]:
ar10_copy

array([[10, 11],
       [20, 56],
       [30, 31]])

In [66]:
ar10

array([[10, 11],
       [20, 56],
       [30, 31]])

In [67]:
ar10_copyNew = ar10.copy()

In [68]:
ar10_copyNew

array([[10, 11],
       [20, 56],
       [30, 31]])

In [69]:
ar10_copyNew[0][0] = 345
ar10_copyNew

array([[345,  11],
       [ 20,  56],
       [ 30,  31]])

In [70]:
ar10

array([[10, 11],
       [20, 56],
       [30, 31]])

In [71]:
ar11 = ar10.view()

In [72]:
ar11

array([[10, 11],
       [20, 56],
       [30, 31]])

In [73]:
ar11[2][0] = 765

In [74]:
ar11

array([[ 10,  11],
       [ 20,  56],
       [765,  31]])

In [75]:
ar10

array([[ 10,  11],
       [ 20,  56],
       [765,  31]])