In [1]:
import numpy

In [2]:
x = [1,2,3,4,5,45,3,2,54,23]
arr = numpy.array(x)
arr

array([ 1,  2,  3,  4,  5, 45,  3,  2, 54, 23])

In [3]:
arr1 = numpy.array([1,2,1,32,1,4,3,56,4,5,64,34,5,43,45,435])
arr1

array([  1,   2,   1,  32,   1,   4,   3,  56,   4,   5,  64,  34,   5,
        43,  45, 435])

In [4]:
arr2 = numpy.array([32,34,24,24,24,54,32,34.2,6,75,34,'67'])
print(arr2)

['32' '34' '24' '24' '24' '54' '32' '34.2' '6' '75' '34' '67']


In [5]:
arr2.dtype

dtype('<U32')

### Declaring dtype on creation

In [6]:
arr3 = numpy.array([1,2,3,4,5,6,7], dtype='float64')
arr3

array([1., 2., 3., 4., 5., 6., 7.])

In [7]:
arr4 = numpy.array([1,2,3,4,5,6,7], dtype='U32')
arr4

array(['1', '2', '3', '4', '5', '6', '7'], dtype='<U32')

In [8]:
arr5 = numpy.array(['7', '8'], dtype='float64')

### Generating an array

For generating an array, we use arange function 

In [9]:
arr6 = numpy.arange(0, 10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr7 = numpy.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
arr8 = numpy.arange(0,20,2)
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Generating Array with Zeros and Ones

In [12]:
arr9 = numpy.zeros(5, dtype='int32')
arr9

array([0, 0, 0, 0, 0])

In [13]:
arr10 = numpy.ones(5, dtype='int32')
print(arr10)

[1 1 1 1 1]


## Performing Arithmatic Operation on Array Elements

In [14]:
arr11 = numpy.arange(10,21)
print(arr11)

[10 11 12 13 14 15 16 17 18 19 20]


In [15]:
arr11 + 20

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [16]:
arr11 * 3

array([30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60])

In [17]:
arr12 = numpy.arange(30,51,2)
arr12

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [18]:
print(arr11)
print(arr12)

[10 11 12 13 14 15 16 17 18 19 20]
[30 32 34 36 38 40 42 44 46 48 50]


In [19]:
arr11 + arr12

array([40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70])

In [20]:
arr11 // arr12

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [21]:
arr11 * arr12

array([ 300,  352,  408,  468,  532,  600,  672,  748,  828,  912, 1000])

In [22]:
arr13 = arr11 + arr12
arr13

array([40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70])

### CRUD Operations 

In [23]:
arr14 = numpy.arange(20,45,3)
arr14

array([20, 23, 26, 29, 32, 35, 38, 41, 44])

In [24]:
arr14[3] += 3

In [25]:
arr14

array([20, 23, 26, 32, 32, 35, 38, 41, 44])

Delete Operations

In [26]:
arr14

array([20, 23, 26, 32, 32, 35, 38, 41, 44])

In [27]:
numpy.delete(arr14, 5) # Deleting a single element

array([20, 23, 26, 32, 32, 38, 41, 44])

In [28]:
arr14 = numpy.delete(arr14, 5)
arr14

array([20, 23, 26, 32, 32, 38, 41, 44])

In [29]:
arr14 = numpy.delete(arr14, [1,3,5])
arr14

array([20, 26, 32, 41, 44])

Adding New Elements in an existing array

In [30]:
arr14

array([20, 26, 32, 41, 44])

In [31]:
arr14 = numpy.append(arr14, 65) # Appending single element
arr14

array([20, 26, 32, 41, 44, 65])

In [32]:
# Appending Multiple Elements
arr14 = numpy.append(arr14, [23,53,23,64,23,57]) 
arr14

array([20, 26, 32, 41, 44, 65, 23, 53, 23, 64, 23, 57])

### Practice Program

Write a Program to generate array of 20 random numbers. 
    Range of each element will be between 0, 1000

In [33]:
import random
lst = []
for i in range(20):
    lst.append(random.randint(0, 1000))
print(lst)
arr15 = numpy.array(lst, dtype='int32')
arr15

[752, 964, 28, 545, 323, 868, 786, 263, 374, 187, 752, 397, 859, 345, 888, 413, 140, 166, 553, 625]


array([752, 964,  28, 545, 323, 868, 786, 263, 374, 187, 752, 397, 859,
       345, 888, 413, 140, 166, 553, 625])

In [34]:
arr16 = numpy.array([], dtype='int32')
size = 0
while size<=20:
    arr16 = numpy.append(arr16, random.randint(0,1000))
    size += 1
arr16

array([336, 267, 247, 658, 971, 675, 254, 780, 142, 209, 874, 714, 576,
       291, 684, 695, 997, 880,  99, 255, 286])

## Time and Space Comparison between list and array 

#### Space Comparison

In [35]:
import sys

lst1 = list(range(1,1000001))

arr17 = numpy.arange(1, 1000001)

print('Size of List ', sys.getsizeof(lst1))
print('Size of Array ', sys.getsizeof(arr17))

Size of List  8000056
Size of Array  4000104


#### Time Comparison

In [36]:
import time

size = 10000000

list1 = list(range(size))
list2 = list(range(size))

array1 = numpy.array(list1)
array2 = numpy.array(list2)

In [37]:
initial_list_time = time.time()
new_list = [(a*b) for a,b in zip(list1, list2)]
resultant_list_time = time.time()

print('Time taken by list in second ', resultant_list_time-initial_list_time)

Time taken by list in second  1.2700040340423584


In [38]:
initial_array_time = time.time()

new_array = array1 * array2

resultant_array_time = time.time()

print('Time taken by array in second', resultant_array_time-initial_array_time)

Time taken by array in second 0.02013397216796875
