In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1,2,3,4,5],
    [5,6,7,8,9],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [10,11,12,13,14]
])
arr

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8,  0],
       [10, 11, 12, 13, 14]])

#### Slicing the Array
array_name[index_of_subarray,index_of_elements]

In [3]:
arr[3,4]

0

In [4]:
arr[-1,-3]

12

In [5]:
arr[1:3, 1:4]

array([[6, 7, 8],
       [3, 5, 7]])

In [6]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8,  0],
       [10, 11, 12, 13, 14]])

In [7]:
arr[::-1, ::]

array([[10, 11, 12, 13, 14],
       [ 2,  4,  6,  8,  0],
       [ 1,  3,  5,  7,  9],
       [ 5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5]])

In [8]:
arr[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 0,  8,  6,  4,  2],
       [ 9,  7,  5,  3,  1],
       [ 9,  8,  7,  6,  5],
       [ 5,  4,  3,  2,  1]])

In [9]:
arr[0:5:2, 0:5:3]

array([[ 1,  4],
       [ 1,  7],
       [10, 13]])

## Joining the Array

In [10]:
arr1 = np.array([1,2,3,4],dtype='int32')
arr2 = np.array([5,6,7,8],dtype='int32')

In [11]:
arr3 = np.concatenate((arr1, arr2))
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Joining 2-D array

In [12]:
arr11 = np.array([[1,2,3,4], [2,3,4,5]])
arr12 = np.array([[4,5,6,7], [5,6,7,8]])
#Joining array on rows
arr13 = np.concatenate([arr11, arr12])
arr13

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [13]:
#Joining array over columns
arr14 = np.concatenate([arr11, arr12],axis=1)
arr14

array([[1, 2, 3, 4, 4, 5, 6, 7],
       [2, 3, 4, 5, 5, 6, 7, 8]])

### Splitting an Array

In [14]:
arr21 = np.array([1,2,3,4,5,6,7,8,8,9,8,5,3,2,5,6])
arr21

array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 8, 5, 3, 2, 5, 6])

In [15]:
arr22 = np.array_split(arr21, 4)
arr22

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([8, 9, 8, 5]),
 array([3, 2, 5, 6])]

In [16]:
arr23 = np.split(arr21, 4)
arr23

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([8, 9, 8, 5]),
 array([3, 2, 5, 6])]

In [17]:
arr24 = np.array_split(arr21, 5)
arr24

[array([1, 2, 3, 4]),
 array([5, 6, 7]),
 array([8, 8, 9]),
 array([8, 5, 3]),
 array([2, 5, 6])]

In [18]:
# unlike array_split,
#split function can not split the main array
#into arrays of different shape
# arr25 = np.split(arr21, 5)
# arr25

#### Spliting 2-D Array

In [19]:
arr26 = np.array([
 [1,2,3,4,5],
 [5,6,7,8,9],
 [1,3,5,7,9],
 [2,4,6,8,0],
 [10,11,12,13,14]
])
arr26

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8,  0],
       [10, 11, 12, 13, 14]])

In [20]:
#Splitting Array on rows
arr27 = np.array_split(arr26, 3)
for i in arr27:
    print('Array',i)

Array [[1 2 3 4 5]
 [5 6 7 8 9]]
Array [[1 3 5 7 9]
 [2 4 6 8 0]]
Array [[10 11 12 13 14]]


In [25]:
#Splitting array on columns
arr28 = np.array_split(arr26, 3, axis=1)
for i in arr28:
    print('Array',i,i.shape)

Array [[ 1  2]
 [ 5  6]
 [ 1  3]
 [ 2  4]
 [10 11]] (5, 2)
Array [[ 3  4]
 [ 7  8]
 [ 5  7]
 [ 6  8]
 [12 13]] (5, 2)
Array [[ 5]
 [ 9]
 [ 9]
 [ 0]
 [14]] (5, 1)


## Searching in Array

In [26]:
arr31 = np.array([1,2,3,4,5,6,7,42,25,3,25,3,5])
arr31

array([ 1,  2,  3,  4,  5,  6,  7, 42, 25,  3, 25,  3,  5])

In [27]:
pos = np.where(arr31 == 4)
pos

(array([3], dtype=int64),)

In [28]:
np.where(arr31 == 5)

(array([ 4, 12], dtype=int64),)

In [29]:
#Returns index of all even numbers
np.where(arr31%2 == 0)

(array([1, 3, 5, 7], dtype=int64),)

In [30]:
#Returns index of all odd numbers
np.where(arr31%2 != 0)

(array([ 0,  2,  4,  6,  8,  9, 10, 11, 12], dtype=int64),)

### Searching on 2-D Array

In [32]:
arr32 = np.array([
 [1,2,3,4,5],
 [5,6,7,8,9],
 [1,3,5,7,9],
 [2,4,6,8,0],
 [10,11,12,13,14]
])
arr32

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8,  0],
       [10, 11, 12, 13, 14]])

In [33]:
np.where(arr32 == 12)

(array([4], dtype=int64), array([2], dtype=int64))

In [34]:
np.where(arr32 == 9)

(array([1, 2], dtype=int64), array([4, 4], dtype=int64))

## Sorting an Array

In [37]:
arr41 = np.array([1,2,3,4,5,6,7,42,25,3,25,3,5])
arr41

array([ 1,  2,  3,  4,  5,  6,  7, 42, 25,  3, 25,  3,  5])

In [38]:
arr42 = np.sort(arr41)
arr42

array([ 1,  2,  3,  3,  3,  4,  5,  5,  6,  7, 25, 25, 42])

### Sorting 2-D Array

In [39]:
arr43 = np.array([
 [1,2,3,4,5],
 [5,6,7,8,9],
 [1,3,5,7,9],
 [2,4,6,8,0],
 [10,11,12,13,14]
])
arr43

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8,  0],
       [10, 11, 12, 13, 14]])

In [40]:
arr44 = np.sort(arr43)
arr44

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 1,  3,  5,  7,  9],
       [ 0,  2,  4,  6,  8],
       [10, 11, 12, 13, 14]])