In [2]:
import numpy

In [14]:
x = [1,2,4,1,3,5,3,5,2,5,3]
arr = numpy.array(x)
print(x)
print(arr)

[1, 2, 4, 1, 3, 5, 3, 5, 2, 5, 3]
[1 2 4 1 3 5 3 5 2 5 3]


In [15]:
print(arr.dtype)

int32


In [17]:
arr

array([1, 2, 4, 1, 3, 5, 3, 5, 2, 5, 3])

## Indexing an Array 

In [18]:
arr[2]

4

In [19]:
print(arr[5])

5


In [20]:
arr[-9]

4

In [22]:
for i in range(0, len(arr)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [24]:
for i in arr:
    print(i)

1
2
4
1
3
5
3
5
2
5
3


## Slicing through array

In [25]:
arr

array([1, 2, 4, 1, 3, 5, 3, 5, 2, 5, 3])

In [26]:
arr[0:5]

array([1, 2, 4, 1, 3])

In [27]:
arr[0:8:2]

array([1, 4, 3, 3])

In [28]:
arr[::-1]

array([3, 5, 2, 5, 3, 5, 3, 1, 4, 2, 1])

In [29]:
arr[-7:-1]

array([3, 5, 3, 5, 2, 5])

In [30]:
arr[8:1:-1]

array([2, 5, 3, 5, 3, 1, 4])

In [32]:
arr[5:1]

array([], dtype=int32)