In [1]:
!pip install numpy

In [3]:
import numpy

In [5]:
x = [1,2,3,4,5,6,7]
arr = numpy.array(x)
# print(arr)
arr //dump // done at end always

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
print(arr.dtype)

int32


In [8]:
arr2 = numpy.array([1,2.0,"hello"])
print(arr2.dtype)

<U32


### Indexing an Array 

In [9]:
arr[2]

3

In [10]:
arr[-9]

IndexError: index -9 is out of bounds for axis 0 with size 7

In [11]:
arr[-3]

5

In [12]:
for i in range(0, len(arr)):
    print(arr[i])

1
2
3
4
5
6
7


In [13]:
for i in arr:
    print(i)

1
2
3
4
5
6
7


## Slicing through array

In [14]:
arr


array([1, 2, 3, 4, 5, 6, 7])

In [15]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [16]:
arr[0:5:2]

array([1, 3, 5])

In [17]:
arr[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [18]:
arr[5:1] //infinite loop

array([], dtype=int32)

In [19]:
print(type(arr)

SyntaxError: unexpected EOF while parsing (2218528896.py, line 1)

In [20]:
print(type(arr))

<class 'numpy.ndarray'>


In [21]:
print(arr.dtype) //datatype in an array

int32
