In [2]:
import numpy as np #Alias

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr.shape #columns

(10,)

### 2-D Array

In [6]:
lst = [
    [1,2,3,4],
    [5,6,7,8]
]
arr2 = np.array(lst)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr2.shape

(2, 4)

In [8]:
arr2.ndim #For dimensions

2

### Changing Shape of Array

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr.shape

(10,)

In [11]:
arr3 = arr.reshape(2,5) #(2,5) multiplication result should be equal to 10

In [12]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
arr3 = arr.reshape(5,2)
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Iterating 2-D Array

In [16]:
arr3.shape

(5, 2)

In [17]:
print('Rows - ', arr3.shape[0])
print('Columns - ', arr3.shape[1])

Rows -  5
Columns -  2


#### Indexing of 2-D Array

In [22]:
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [23]:
print(arr3[0])

[1 2]


In [24]:
print(arr3[0][0])

1


In [25]:
print(arr3[3]) #Prints 4th element of the main array

[7 8]


In [26]:
print(arr3[3][1]) #Prints 2nd element of subarray number4

8


In [28]:
for row in range(0, arr3.shape[0]): #0,5
    for col in range(0, arr3.shape[1]): #0,2
        print(arr3[row][col],end=' ')
    print()

1 2 
3 4 
5 6 
7 8 
9 10 


### Arithmatic Operations on Metrics

#### Addition

In [29]:
met1 = np.array([[1,3,4], [2,4,3], [3,4,5]]) #matrix 1
met2 = np.array([[1,3,4], [2,4,3], [1,2,4]]) #matrix 2

In [31]:
met3 = met1 + met2
print(met3)

[[2 6 8]
 [4 8 6]
 [4 6 9]]


In [33]:
met4 = np.add(met1, met2)
print(met4)

[[2 6 8]
 [4 8 6]
 [4 6 9]]


#### Subtraction

In [34]:
met1 = np.array([[2,4,6], [4,2,2], [2,4,2]])
met2 = np.array([[1,2,3], [2,1,1], [1,2,1]])

In [35]:
met3 = met1 - met2
print(met3)

[[1 2 3]
 [2 1 1]
 [1 2 1]]


In [36]:
met4 = np.subtract(met1, met2)
print(met4)

[[1 2 3]
 [2 1 1]
 [1 2 1]]


In [37]:
#list is always 1-d but array can be 2-d or 3-d

#### Multiplication 

In [38]:
met1 = np.array([[1,2,3], [4,5,6]])
met2 = np.array([[10,11], [20,21], [30,31]])

In [39]:
met3 = met1*met2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [40]:
met3 = np.multiply(met1, met2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [41]:
met3 = np.dot(met1, met2)
print(met3)

[[140 146]
 [320 335]]


### Copy an Array

In [42]:
arr10 = np.array([[10,11], [20,21], [30,31]])

In [43]:
arr10

array([[10, 11],
       [20, 21],
       [30, 31]])

In [46]:
arr10_copy = arr10

In [47]:
arr10_copy #It is creating a reference not a copy

array([[10, 11],
       [20, 21],
       [30, 31]])

In [48]:
arr10_copy[1][1] = 56

In [49]:
arr10_copy

array([[10, 11],
       [20, 56],
       [30, 31]])

In [50]:
arr10

array([[10, 11],
       [20, 56],
       [30, 31]])

In [51]:
arr10_copyNew = arr10.copy() #Create a copy

In [52]:
arr10_copyNew

array([[10, 11],
       [20, 56],
       [30, 31]])

In [53]:
arr10_copyNew[0][0] = 345
arr10_copyNew

array([[345,  11],
       [ 20,  56],
       [ 30,  31]])

In [54]:
arr10

array([[10, 11],
       [20, 56],
       [30, 31]])

In [55]:
arr11 = arr10.view() #creates a reference

In [56]:
arr11

array([[10, 11],
       [20, 56],
       [30, 31]])

In [57]:
arr11[2][0] = 756
arr11

array([[ 10,  11],
       [ 20,  56],
       [756,  31]])

In [58]:
arr10

array([[ 10,  11],
       [ 20,  56],
       [756,  31]])